---

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    shm_size: 800m  # Increase shared memory size
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    dns:
      - 127.0.0.1
      - 8.8.8.8
    environment:
      TZ: "Asia/Dhaka"
      WEBPASSWORD: "r@nd0mpa$$"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
      - "./02-custom-settings.conf:/etc/dnsmasq.d/02-custom-settings.conf"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
